parameters:
  buildConfiguration: 'Release'

steps: 
- task: DotNetCoreCLI@2 
  displayName: 'Build the project - ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'

- task: 
  displayName: 'Publish the project =${{ parameters.Buildconfiguration }}'
  inputs: 
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false 
    arguments: '--no-build --configuration ${{ parameters.BuildConfiguration }} --output $(Build.ArtifactStagignDirectory)/${{ parameters.buildConfiguration}}' 
    zipafterpublish: true 
